name: Build Project

env:
  AUTH_TIENDANUBE: ${{ secrets.AUTH_TIENDANUBE }}
  AUTH_SHIPNOW: ${{ secrets.AUTH_SHIPNOW }}
  AUTH_MERCADOPAGO: ${{ secrets.AUTH_MERCADOPAGO }}
  AUTH_MELI_REFRESH_TOKEN: ${{ secrets.AUTH_MELI_REFRESH_TOKEN }}
  AUTH_MELI_CLIENT_SECRET: ${{ secrets.AUTH_MELI_CLIENT_SECRET }}
  AUTH_MELI_CLIENT_ID: ${{ secrets.AUTH_MELI_CLIENT_ID }}
  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
  GOOGLE_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
  GOOGLE_CLIENT_CERT: ${{ secrets.GOOGLE_CLIENT_CERT }}
  GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Build Project
        run: npm build
      - name: Start Project
        run: npm start
