name: Automatic Run

env:
  AUTH_TIENDANUBE: ${{ secrets.AUTH_TIENDANUBE }}
  AUTH_SHIPNOW: ${{ secrets.AUTH_SHIPNOW }}
  AUTH_MERCADOPAGO: ${{ secrets.AUTH_MERCADOPAGO }}
  AUTH_MELI_REFRESH_TOKEN: ${{ secrets.AUTH_MELI_REFRESH_TOKEN }}
  AUTH_MELI_CLIENT_SECRET: ${{ secrets.AUTH_MELI_CLIENT_SECRET }}
  AUTH_MELI_CLIENT_ID: ${{ secrets.AUTH_MELI_CLIENT_ID }}
  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
  GOOGLE_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_PRIVATE_KEY_ID }}
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
  GOOGLE_CLIENT_CERT: ${{ secrets.GOOGLE_CLIENT_CERT }}
  GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook
  schedule:
    - cron: '30 7,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          node Scripts/index.js
          git config user.name apiep
          git config user.name agusiglesias72@gmail.com
          git add -A
          git commit -m "[apiep] Update Sales"
          git push origin main
