name: Automatic Run

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          node Scripts/index.js
          git config user.name apiep
          git add -A
          git commit -m "[apiep] Update Sales"
          git push origin main
